CSTest/Models/AllData.cs
namespace CSTest.Models {
    public class AllData {
        public int id { get; set; }
        public double temperature { get; set; }
        public double price { get; set; }
        public double consumptionHouse { get; set; }
        public double consumptionPlant { get; set; }
        public string userName { get; set; }
    }
}

CSTest/Models/DateTemp.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CSTest {
    public class DateTemp {
        [Key]
        public int id { get; set; }
        public int daysNumber { get; set; }
        public DateTime dateTime { get; set; }
        public double temperature { get; set; }

        public static DateTime zeroCountDateTime = new DateTime(1970, 1, 1); //unix time
    }
}

CSTest/Models/ForecastModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSTest.Models {
    public class ForecastModel {
        public DateTime date { get; set; }
        public double[] consuption { get; set; }
        public double forecast { get; set; }

    }
}

CSTest/Models/HouseDetail.cs
using CSTest.Models;
using System;
using System.ComponentModel.DataAnnotations;

namespace CSTest {
    public class HouseDetail {
        [Key]
        public int id { get; set; }
        public int daysNumber { get; set; }
        public HouseName houseName { get; set; }
        public double consumptionHouse { get; set; }
        public DateTime localDateTemp { get; set; }
        public string userName { get; set; }
    }
}

CSTest/Models/HouseName.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CSTest.Models {
    public class HouseName {
        [Key]
        public int id { get; set; }
        public string name { get; set; }
        public List<HouseDetail> listHouseDetails { get; set; }

        public HouseName() {
            listHouseDetails = new List<HouseDetail>();
        }
    }
}

CSTest/Models/PlantDetail.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CSTest.Models {
    public class PlantDetail {
        [Key]
        public int id { get; set; }
        public int daysNumber { get; set; }
        public PlantName plantName { get; set; }
        public double price { get; set; }
        public double consumptionPlant { get; set; }
        public DateTime localDateTemp { get; set; }
        public string userName { get; set; }
    }
}

CSTest/Models/PlantName.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CSTest.Models {
    public class PlantName {
        [Key]
        public int id { get; set; }
        public string name { get; set; }
        public List<PlantDetail> listPlantDetails { get; set; }

        public PlantName() {
            listPlantDetails = new List<PlantDetail>();
        }
    }
}

CSTest/Controllers/ForecastController.cs
using System.Collections.Generic;
using System.Linq;
using CSTest.Data;
using CSTest.Interfaces;
using CSTest.Models;
using Microsoft.AspNetCore.Mvc;

namespace CSTest.Controllers {
    public class ForecastController : Controller {
        private IHouseDetailes houseDetailes;
        private IPlantDetailes plantDetailes;
        private Dictionary<int, double> consH;
        private Dictionary<int, double> consP;
        private List<double> consuptions { get; set; }
        private List<double> consuptionsLimit { get; set; }
        public ForecastModel forecastModel { get; set; }


        public ForecastController(IHouseDetailes houseDetailes, IPlantDetailes plantDetailes) {
            this.houseDetailes = houseDetailes;
            this.plantDetailes = plantDetailes;
            consH = new Dictionary<int, double>();
            consP = new Dictionary<int, double>();

            consuptions = new List<double>();
            consuptionsLimit = new List<double>();

            foreach (HouseDetail h in houseDetailes.getHouseDetails) {
                if (!consH.ContainsKey(h.daysNumber)) consH.Add(h.daysNumber, h.consumptionHouse);
                else consH[h.daysNumber] = consH[h.daysNumber] + h.consumptionHouse;
            }
            foreach (PlantDetail p in plantDetailes.getPlantDetails) {
                if (!consP.ContainsKey(p.daysNumber)) consP.Add(p.daysNumber, p.consumptionPlant);
                else consP[p.daysNumber] = consP[p.daysNumber] + p.consumptionPlant;
            }
            foreach (KeyValuePair<int, double> pair in consH) {
                consuptions.Add(pair.Value + consP[pair.Key]);
            }
            forecastModel = new ForecastModel();
            if (consuptions.Count >= 7) {
                for (int i = consuptions.Count - 7; i < consuptions.Count; i++) { //last 7 days
                    consuptionsLimit.Add(consuptions[i]);
                }
                forecastModel.consuption = consuptionsLimit.ToArray();
                forecastModel.forecast = new MNK().calc(consuptionsLimit.ToArray(), 3);
                forecastModel.date = DateTemp.zeroCountDateTime.AddDays(plantDetailes.getPlantDetails.Last().daysNumber + 1);
            }
        }

        public IActionResult Index() {
            return View(forecastModel);
        }
    }
}

CSTest/Controllers/LoadController.cs
using Microsoft.AspNetCore.Mvc;

namespace CSTest.Controllers {
    public class LoadController : Controller {
        public ViewResult Index() {
            return View();
        }
    }
}

CSTest/Controllers/UploadFilesController.cs
using CSTest.Interfaces;
using CSTest.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace CSTest.Controllers {
    public class UploadFilesController : Controller {
        List<AllData> allDatas = new List<AllData>();
        private IFileOperations _fileOperations;
        public UploadFilesController(IFileOperations fileOperations) {
            _fileOperations = fileOperations;
        }

        [HttpPost]
        public IActionResult AddFiles() {
            if (Request.Form.Files.Count > 0) {
                foreach (var file in Request.Form.Files) {
                    if (file != null && file.Length > 0) {
                        _fileOperations.parseXml(file.OpenReadStream());
                    }
                }
            }
            return RedirectToAction("Index", "Home", new { });
        }
    }
}

CSTest/Views/Forecast/Index.cshtml
@model ForecastModel
@{
    ViewData["Title"] = "Index";
}

<h4>Forecast</h4>
@{ if(Model.consuption != null)
    for(int i = 0; i < Model.consuption.Length; i++) {
        if(i != Model.consuption.Length - 1) {
            <div>
                <p>@Model.consuption[i]</p>
            </div>
        } else {
            <p></p>
            <h5>@Model.date.ToShortDateString()</h5>
            <h4>@Model.forecast</h4>
        }
    };
}

CSTest/Views/Home/Index.cshtml
@using CSTest.Models
@model IEnumerable<AllData>
@{
    Layout = "_Layout";
    ViewData["Title"] = "Index";
}

@{
    var XLabels = Newtonsoft.Json.JsonConvert.SerializeObject(Model.Select(a => a.id).ToList());
    var YHLabels = Newtonsoft.Json.JsonConvert.SerializeObject(Model.Select(a => a.consumptionHouse).ToList());
    var YPLabels = Newtonsoft.Json.JsonConvert.SerializeObject(Model.Select(a => a.consumptionPlant).ToList());
}

<body>

    <script src="~/js/Chart.bundle.js"></script>
    <script src="~/js/Chart.bundle.min.js"></script>
    <script src="~/js/Chart.js"></script>
    <script src="~/js/Chart.min.js"></script>

    <div class="content">
        <div class="wrapper">
            <canvas id="allDataChart" width="400" height="200"></canvas>
        </div>
        <div class="toolbar">
            
        </div>
        <div id="chart-analyser" class="analyser"></div>
    </div>

    <script>
            var ctx = document.getElementById('allDataChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: @XLabels,
                    datasets: [{
                        label: '# Houses consuption',
                        borderColor: 'rgba(255, 99, 132, 1)',
                        data: @YHLabels,
                        borderWidth: 1
                    },
                        {
                            label: '# Plants consuption',
                            borderColor: 'rgba(54, 162, 235, 1)',
                            data: @YPLabels,
                            borderWidth: 1
                        }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            stacked: true,
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    },
                     elements: {
                        line: {
                        tension: 0
                        }
                    }
                }
            });
    </script>
</body>

CSTest/Views/Load/Index.cshtml
<form method="post" enctype="multipart/form-data"
      asp-controller="UploadFiles"
      asp-action="AddFiles">
    <div class="form-group">
        <div class="col-md-10">
            <p>Upload one or more files using this form:</p>
            <input type="file" name="file">
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Upload">
        </div>
    </div>
</form>

CSTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CSTest</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CSTest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Load" asp-action="Index">Upload</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Forecast" asp-action="Index">Forecast</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - CSTest -
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>